image:
  credential: false

stratum:
  nodeSelector:
    node-role.aetherproject.org: switch

  tolerations:
    - effect: NoSchedule
      value: switch
      key: node-role.aetherproject.org

  podsecuritypolicy:
    enabled: false
  external_chassis_config: true

import:
  onos-classic:
    enabled: false
  pfcp-agent:
    enabled: false
