apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: opensearch-basic-auth
  namespace: logging-system
spec:
  encryptedData:
    password: AgBxSymBQZoRUjifBfz9fBEdlCBxs7gpmym+U2H5ehNtUidqFb8nvYIjC18p+TB7PWKX2jgYtEg0n8iBKgKZcur/nxiN1JuN9VugP2ple3myt7851Fqzf9KXV0XztfMEH0UMCBPA3kq4qQPzOLgOHj3QT4kf2T8tI6Mo/3eNjamFTwTXZMaYaaPNKz6i37CotAlor0nBJRNdsTFasGK/5UJbE+z+F2jVvyLxS4MCir16YuzWOucnBZNa+nX1zHVTwzXBXiShWtUjIfnPouzTy9/EcPC6hQrzWqihkBQAMJ/xQi1fhLqRxyzDPosLrGmrjABOoE1hdvPx+0gTGW6Mhr5Eup6VlRW4MTN1Ik+w3kWc8tIwmIAWYKDOgwlbMD8mu9U6i9g1JiAmLR8GutNVHSJ1Eub+R9BxJwRwrp028UYHM9nslQjX77qptteV/A82/EgQdBIqvSHIPK5ZTjz9tYB52PTawsNk8xuHXynz0CH993w4CO33Pz/L2F+gM/VXCPhFSpc4CAApRwilPEN4bLrH9HSJGo+05B8570lv4Reho+65UnnhzVNDuwbLNyx7ZVA+ol0Z2Wd+Iag1WDSLm6binczFh9h6E6aLnPZGiuuv/sa4tM4RWJvBOuor8jRm/wU7BBK5KACnKWDzUtMnsfDSt6ymy8AdDhm8eNVS7Fp4Cj6ah6APcjaLWoioz5c/Cbi05aLuGQ==
    username: AgC1BlwfV1dI/EBiRn9849kwjEWYjmuS0r8Le137wrz8VZVX715Sg8GdYz6yfFlGI/JnljhdpO0ncBwLBzjsNt5rUnCNSsDsSmAuMKKX1HgJeF8Mh/nfDt/yN8XGgvwPi3eLfg/JEDYgYJCGJz8scwBc2Uhn/O+KxXtkf4C/R9tZoado/S6GYnPXHBOlFIw9Doh5bKLbk38zud/eyXlhPR8HaVCGoOfjGlpKUX+h4pVmAtxZ1CpUe/8sqK2VxJcE5ajp7E3gwEcnwF0NNk2WghKZ1r8eAGTca7eqX5lhgaEOJlcgJ6Z7suhJUtiUTo2tW2sRgxL49cAa+UuUvheXXW1ST7ac8u0OxWkzKd7J10m0Oa+0LNCrroownj4JPcX0g9PAvzjTtURbLk5yChVbsJEig/MoXsDVJib59vRn5wc6qRBoBIWesVh9zGJB9wl5qt4VW+uNS1yjV0jVzZrwxsv73ysY9wwKRvdO65ij4kwYkOzY4J9LGiFiJ1E9I0vDKVOKsyoBjLtSLA2CjAFK0K6V3LUY6KAWbZroH0gKGCBtQFOMC5sHDxFlJvIcj4e/xqa8qgAZhQQGBjJQL0zZwpC7E8EwKaTOO2JPPlSXuyLNIMsf38++Gn+I+/2y25R+ROm2ratJMMCypK1ojLPDOgVC3DpwVsR+dxYjXPGOdbI96tUYXRjOIxB3eZ7AThNBAmioZuAlsg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: opensearch-basic-auth
      namespace: logging-system
    type: kubernetes.io/basic-auth
