apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-sample-config
data:
  postgresql.conf.sample: |-
    huge_pages = off
    wal_level = 'replica'
    archive_mode = 'on'
    archive_command = '/bin/true'
    max_wal_senders = '16'
    max_replication_slots = '10'
    hot_standby = 'on'
    logging_collector = 'on'
    log_directory = '/opt/bitnami/postgresql/logs'
    log_filename = 'postgresql.log'
    log_connections = 'false'
    log_disconnections = 'false'
    log_hostname = 'true'
    client_min_messages = 'error'
    include_dir = '/opt/bitnami/postgresql/conf/conf.d'
    pgaudit.log_catalog = 'off'
