kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: system-services
  namespace: fleet-default
spec:
  repo: https://github.com/hyunsun/aether-configs
  branch: main
  paths:
    - infra/sealed-secrets
    - infra/rancher-monitoring-crd
    - infra/rancher-monitoring
    - infra/fluent-bit
    - infra/opensearch
    - infra/opensearch-dashboard
    - infra/opensearch-config
    - infra/hostpath-provisioner
    - infra/sriov-device-plugin
    - infra/metallb
    - infra/keycloak
    - infra/external-dns
  targets:
    - clusterSelector: {}
