apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-dhcp-cni-ds
  labels:
    app: dhcp-cni
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: dhcp-cni
  template:
    metadata:
      labels:
        app: dhcp-cni
        name: dhcp-cni
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: kube-dhcp-cni
          image: mellanox/dhcp-cni
          securityContext:
            privileged: true
          command:
            - /bin/sh
          args:
            - -c
            - 'rm -f /run/cni/dhcp.sock; exec /dhcp daemon'
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          volumeMounts:
            - name: run
              mountPath: /run
            - name: optcnibin
              mountPath: /host/optcnibin
      volumes:
        - name: run
          hostPath:
            path: /run
        - name: optcnibin
          hostPath:
            path: /opt/cni/bin
