apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns
data:
  Corefile: |-
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        k8s_gateway aetherproject.net in-addr.arpa ip6.arpa {
          resources Ingress Service
          fallthrough in-addr.arpa ip6.arpa
        }
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
