apiVersion: v1
kind: Service
metadata:
  name: external-dns
spec:
  type: LoadBalancer
  loadBalancerIP: 10.92.2.166
  selector:
    k8s-app: "external-dns"
  ports:
    - {port: 53, protocol: UDP, name: udp-53}
